chore: polish Periphery v2 deployment script
sense-finance/sense-v1 pull request #364
Opened 2023-07-20 11:17 UTC by fedealconada

## Motivation

Improve deployment script for Periphery V2 and add sanity checks

## Solution

Deployment script has been updated to include some sanity checks (basically, checking that we can `roll()` on the new Periphery).

Friendly reminder on how to run the deployment script in fork mode:
```
cd /sense-v1/pkg/deployments
yarn task 20230301-periphery-v2 --network hardhat
```

## Implementer Checklist

- [ ]  [OPTIONAL] Create a reference implementation (in python or JS)
- [x]  Create a short "Motivation" section for the PR
- [x]  Write a spec for the feature and put it in the PR description – basic function names and expected state transitions is OK
- [ ]  Get the PR reviewed by at least two people

If this is your first time reviewing smart contract changes
- [ ]  Review the [Solcurity](https://github.com/Rari-Capital/solcurity) standard

If smart contract changes were made
- [ ]  Check all of the new revert paths with concrete tests
- [ ]  Check all of the new storage slot writes with concrete tests – do not make the passing test case the trivial case!
- [ ]  Go line-by-line through the new code and ensure it has all been covered by concrete tests – since we don’t have a coverage engine for foundry yet, you can imagine how one might check that each different code path is covered
- [ ]  Simplify the implementation and spend some time trying to minimize gas costs
- [ ]  Write fuzz tests for the feature – try everything to break the implementation (is this function monotonically in/decreasing, should it always be less than something else, etc)
- [ ]  Capture bugs discovered during the above steps in concrete tests (regression tests)
- [ ]  Add integration tests – fuzz or concrete tests that test how the new code affects the entire system, either locally or with a mainnet fork
- [ ]  [OPTIONAL] Integrate the feature into the deployment scripts
- [ ]  [OPTIONAL] Add new sanity checks to the deployment scripts

If your PR uses or interacts with prices of any kind
- [ ] Make sure forge is running the test on the latest block
- [ ] Compare the value returned with some other source (like Curve)
- [ ] Check the `updatedAt` (if available) value of the contract and confirm that the price we are sourcing is in fact not older than X
- [ ] Ensure oracle liveness from the oracle maintainer, either through a public status interface or through written confirmation from a developer.

2023-07-20 13:59 UTC, stevenvaleri requested changes
Overall looks good - a couple of questions / thoughts that may not need code changes.

2023-07-20 13:59 UTC, stevenvaleri commented on pkg/deployments/tasks/20230301-periphery-v2/index.js
> +    console.log("\nOnboarding adapter", adapter);
"Verifying Adapter" instead of onboarding in this step

2023-07-20 13:59 UTC, stevenvaleri commented on pkg/deployments/tasks/20230301-periphery-v2/index.js
> +      const rlv = new ethers.Contract(rlvAddress, rlvAbi, multisigSigner);
Around here, i'm getting a message:

`Duplicate definition of ParamChanged (ParamChanged(bytes32,address), ParamChanged(bytes32,uint256))`

My abi's might be off from an old compile. I don't think it would cause an issue, curious if you have this though.

2023-07-20 13:59 UTC, stevenvaleri commented on pkg/deployments/tasks/20230301-periphery-v2/index.js
> +      if (await oldPeriphery.isTrusted(senseAdminMultisigAddress)) {
Are there risks to removing the multi-sig at this point? If something were to go wrong in this process, would there be benefit to delaying the removal of the multi-sig as admin until we confirm the migration to the new periphery has been 100% successful?

2023-07-20 13:59 UTC, stevenvaleri commented on pkg/deployments/tasks/20230301-periphery-v2/index.js
> +      console.log(`- Skipping RLV ${rlv.address} as we couldn't generate target tokens for it`);
3 / 8 successfully rolled, the rest are skipped for this reason. Is there another way to easily generate the tokens so that these can be tested - maybe sending from a whale's address. Likely low risk here though given there are successful rolls.

2023-07-24 10:59 UTC, fedealconada commented on pkg/deployments/tasks/20230301-periphery-v2/index.js
> +      const rlv = new ethers.Contract(rlvAddress, rlvAbi, multisigSigner);
I have seen this before but not experiencing it right now

>  I don't think it would cause an issue
agree

2023-07-24 11:02 UTC, fedealconada commented on pkg/deployments/tasks/20230301-periphery-v2/index.js
> +      if (await oldPeriphery.isTrusted(senseAdminMultisigAddress)) {
I agree this can wait!

2023-07-24 11:04 UTC, fedealconada commented on pkg/deployments/tasks/20230301-periphery-v2/index.js
> +      console.log(`- Skipping RLV ${rlv.address} as we couldn't generate target tokens for it`);
Yeah, that could be a solution. Or sometimes is just generating tokens for the underlying of the token wanted and then wrapping or things like that. I didn't want to spend that much time and thought that having just 2-3 working cases was fine. 
The idea was more to do an E2E test making sure that the change of Periphery was working fine with the existing RLVs.

2023-07-24 12:51 UTC, stevenvaleri approved these changes
Looks good!

2023-07-24 14:29 UTC, merged